---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: 1.0.0
servers:
  - url: /api/spa/v1
    description: Generated server url
paths:
  /task/{id}:
    put:
      tags:
        - Task
      operationId: updateTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TaskRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TaskResponse"
    delete:
      tags:
        - Task
      operationId: deleteTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /task:
    get:
      tags:
        - Task
      operationId: getTask
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/TaskListResponse"
    post:
      tags:
        - Task
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TaskRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TaskResponse"
  /security/user:
    post:
      tags:
        - User
      operationId: login
      parameters:
        - name: user
          in: query
          required: true
          schema:
            type: string
        - name: password
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserResponse"
components:
  schemas:
    TaskRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        detail:
          type: string
        status:
          type: integer
          format: int32
    TaskResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
    UserResponse:
      type: object
      properties:
        user:
          type: string
        token:
          type: string
    TaskListResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        detail:
          type: string
        status:
          type: string
